/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RThemesSlugRouteImport } from './routes/r/themes/$slug'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RThemesSlugRoute = RThemesSlugRouteImport.update({
  id: '/r/themes/$slug',
  path: '/r/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/themes': typeof ThemesRoute
  '/r/themes/$slug': typeof RThemesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/themes': typeof ThemesRoute
  '/r/themes/$slug': typeof RThemesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/themes': typeof ThemesRoute
  '/r/themes/$slug': typeof RThemesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/themes' | '/r/themes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/themes' | '/r/themes/$slug'
  id: '__root__' | '/' | '/create' | '/themes' | '/r/themes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ThemesRoute: typeof ThemesRoute
  RThemesSlugRoute: typeof RThemesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/themes/$slug': {
      id: '/r/themes/$slug'
      path: '/r/themes/$slug'
      fullPath: '/r/themes/$slug'
      preLoaderRoute: typeof RThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ThemesRoute: ThemesRoute,
  RThemesSlugRoute: RThemesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
